Inventory/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Inventory.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

WOS/WISH/urls.py
"""urls"""
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from . import views
from . import models
from . import cviews

urlpatterns = [
    url(r'^$', login_required(cviews.index), name='index'),
    url(r'^Aboutus/$', login_required(cviews.aboutus), name='aboutus'),

    #URL patterns for Log In and Out (start)
    url(r'^log_in/$', views.log_in, name='login'),
    url(r'^logout/$', login_required(views.log_out), \
        name='logout'),
    url(r'^guest/$', login_required(cviews.index), name='guest'),
    #URL patterns for Log In and Out (end)

    #URL patterns for File and Product Fill-Up Forms (start)
    url(r'^product/new/$', login_required(views.product_new), \
    name='new_product'),
    url(r'^par/(?P<inv>[0-9]+)/$', login_required(views.par), name='new_par'),
    url(r'^par_f/$', login_required(cviews.ParF.as_view()), name='new_par_s'),
    url(r'^irr_entry/$', login_required(views.irr_entry), name='new_irr'),
    url(r'^miv_entry_f/$', login_required(cviews.MivF.as_view()),\
     name='new_miv'),
    url(r'^miv_entry/(?P<pk>[0-9]+)/$', login_required(views.miv_entry), \
        name='new_miv_s'),
    url(r'^garv_entry_f/(?P<user>.*)/$', login_required(cviews.GarvF.as_view()), \
    name='new_garv_s'),
    url(r'^garv_entry_f/$', login_required(cviews.GarvF.as_view()), \
    name='new_garv_s'),
    url(r'^product_to_garv/(?P<pk>[0-9]+)/$', login_required(views.product_to_garv), \
        name='new_garv'),
    url(r'^product_to_irr/(?P<pk>[0-9]+)/(?P<inv>[0-9]+)/(?P<sup>[0-9]+)/$', login_required(\
        views.product_to_irr), name='new_irr_cont'),
    #URL patterns for File and Product Fill-Up Forms (end)

    #URL patterns for File Forms (start)
    url(r'^par_form/(?P<pk>[0-9]+)/$', login_required(views.par_form), \
        name='par_form'),
    url(r'^irr_form/(?P<pk>[0-9]+)/$', login_required(views.irr_form), \
        name='irr_form'),
    url(r'^miv_form/(?P<pk>[0-9]+)/$', login_required(views.miv_form), \
        name='miv_form'),
    url(r'^garv_form/(?P<pk>[0-9]+)/$', login_required(views.garv_form), \
        name='garv_form'),
    url(r'^wrs_form/(?P<pk>[0-9]+)/$', login_required(views.wrs_form), \
        name='wrs_form'),
    #URL patterns for File Forms (end)

    #URL patterns for Editing Libraries (start)
    url(r'^product_form/(?P<pk>[0-9]+)/$', login_required(views.product_form),\
        name='product_entry'),
    url(r'^inv_stat_form/(?P<pk>[0-9]+)/$', \
    login_required(cviews.InvStatEntry.as_view()),\
     name='invstat_entry'),
    url(r'^cost_center_form/(?P<pk>[0-9]+)/$', \
    login_required(cviews.CostCenEntry.as_view()), \
        name='costcen_entry'),
    url(r'^supplier_form/(?P<pk>[0-9]+)/$', \
    login_required(views.supplier_form),\
        name='supplier_entry'),
    url(r'^employee_form/(?P<pk>[0-9]+)/$', \
    login_required(cviews.EmpEntry.as_view()), name='emp_entry'),
    #URL patterns for Editing Libraries (end)

    #URL patterns for Library Details (start)
    url(r'^product_details/(?P<pk>[0-9]+)/$', \
    login_required(cviews.ProdDetails.as_view()),\
     name='prod_details'),
    url(r'^inv_stat_details/(?P<pk>[0-9]+)/$', \
    login_required(cviews.InvStatDetails.as_view()),\
        name='invstat_details'),
    url(r'^cost_center_details/(?P<pk>[0-9]+)/$',\
     login_required(cviews.CCDetails.as_view()), \
        name='costcen_details'),
    url(r'^supplier_details/(?P<pk>[0-9]+)/$',\
     login_required(cviews.SupDetails.as_view()),\
        name='supplier_details'),
    url(r'^employee_details/(?P<pk>[0-9]+)/$', \
    login_required(cviews.EmpDetails.as_view()),\
        name='emp_details'),
    #URL patterns for Library Details (end)

    #URL patterns for Deleting Libraries (start)
    url(r'^inv_stat_del/(?P<pk>[0-9]+)/$', login_required(cviews.inv_stat_del),\
        name='invstat_del'),
    url(r'^cost_center_del/(?P<pk>[0-9]+)/$', \
        login_required(cviews.cost_center_del), name='costcen_del'),
    url(r'^supplier_del/(?P<pk>[0-9]+)/$', login_required(cviews.supplier_del),\
        name='supplier_del'),
    url(r'^employee_del/(?P<pk>[0-9]+)/$', login_required(cviews.employee_del),\
        name='emp_del'),
    #URL patterns for Deleting Libraries (end)

    #URL patterns for Adding Libraries (start)
    url(r'^add_cost_center/$', login_required(cviews.AddCC.as_view()), \
    name='add_cost_center'),
    url(r'^add_inv_stat/$', login_required(cviews.AddInvStat.as_view()),\
     name='add_inv_stat'),
    url(r'^add_supplier/$', login_required(views.add_supplier), name='add_supplier'),
    url(r'^add_employee/$', login_required(cviews.AddEmp.as_view()),\
     name='add_employee'),
    #URL patterns for Adding Libraries (end)

    #URL patterns for File and Product Reports (start)
    url(r'^irr_reports/$', login_required(cviews.IRRRep.as_view()),\
     name='irr_reports'),
    url(r'^miv_reports/$', login_required(cviews.MIVRep.as_view()),\
     name='miv_reports'),
    url(r'^wrs_reports/$', login_required(cviews.WRSRep.as_view()),\
     name='wrs_reports'),
    url(r'^wrs_reports1/$', cviews.WRSRep1.as_view(),\
     name='wrs_reports1'),
    url(r'^par_reports/$', login_required(cviews.PARRep.as_view()),\
     name='par_reports'),
    url(r'^garv_reports/$', login_required(cviews.GARVRep.as_view()),\
     name='garv_reports'),
    url(r'^garv_reports1/$', cviews.GARVRep1.as_view(),\
     name='garv_reports1'),
    url(r'^product_reports/$', login_required(cviews.ProdRep.as_view()),\
     name='product_reports'),
    #for guest (start)
    #url(r'^wrs_entry/$', views.wrs_entry, name='wrs_entry'),
    #for guest (end)
    #URL patterns for File and Product Reports (end)

    #URL patterns for Viewing Libraries (start)
    url(r'^inv_stat/$', login_required(cviews.InvStatRep.as_view()),\
     name='inv_stat'),
    url(r'^cost_center/$', login_required(cviews.CCRep.as_view()),\
     name='cost_center'),
    url(r'^supplier/$', login_required(cviews.SupRep.as_view()),\
     name='supplier'),
    url(r'^employee/$', login_required(cviews.EmpRep.as_view()),\
     name='employee'),

    #URL patterns for view restore libraries
    url(r'^inv_stat_res/$', login_required(cviews.InvStatRes.as_view()),\
     name='inv_stat_res'),
    url(r'^cost_center_res/$', login_required(cviews.CCRes.as_view()),\
     name='cost_center_res'),
    url(r'^supplier_res/$', login_required(cviews.SupRes.as_view()),\
     name='supplier_res'),
    url(r'^employee_res/$', login_required(cviews.EmpRes.as_view()),\
     name='employee_res'),

    #URL patterns for details of restore libraries
    url(r'^inv_stat_details_res/(?P<pk>[0-9]+)/$', \
    login_required(cviews.InvStatDetailsRes.as_view()),\
        name='invstat_details_res'),
    url(r'^cost_center_details_res/(?P<pk>[0-9]+)/$',\
     login_required(cviews.CCDetailsRes.as_view()), \
        name='costcenter_details_res'),
    url(r'^supplier_details_res/(?P<pk>[0-9]+)/$',\
     login_required(cviews.SupDetailsRes.as_view()),\
        name='supplier_details_res'),
    url(r'^employee_details_res/(?P<pk>[0-9]+)/$', \
    login_required(cviews.EmpDetailsRes.as_view()),\
        name='emp_details_res'),

    #URL patterns for restore functionality
    url(r'^inv_stat_res/(?P<pk>[0-9]+)/$', login_required(cviews.inv_stat_res),\
        name='invstat_res'),
    url(r'^cost_center_res/(?P<pk>[0-9]+)/$', login_required(cviews.cost_center_res),\
        name='costcenter_res'),
    url(r'^supplier_res/(?P<pk>[0-9]+)/$', login_required(cviews.supplier_res),\
        name='supplier_res'),
    url(r'^employee_res/(?P<pk>[0-9]+)/$', login_required(cviews.employee_res),\
        name='employee_res'),

    #URL patterns for Viewing Libraries (end)
    url(r'^handson/$', login_required(views.handson),\
        name='handson'),
    url(r'^list_view/$', login_required(views.list_view),\
        name='list_view'),
    url(r'^selectable/', include('selectable.urls'))    
]

WOS/WOS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

#urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'WOS.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

#    url(r'^admin/', include(admin.site.urls)),
#)
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('WISH.urls')),
]

WOS/WISH/models.py
"""models"""
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords
from json_field import JSONField


class Supplier(models.Model):
    """Supplier model"""
    supplier_number = models.CharField(max_length=8)
    supplier_name = models.CharField(max_length=40)
    supplier_address = models.CharField(max_length=40)
    telephone_number = models.CharField(max_length=11, null=True, blank=True)
    credit_limit = models.FloatField()
    debit_amount = models.FloatField()
    credit_amount = models.FloatField()
    balance_amount = models.FloatField()
    contact_person = models.CharField(max_length=20, null=True, blank=True)
    remarks = models.CharField(max_length=20, null=True, blank=True)
    is_delete = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.supplier_number + ", " + self.supplier_name

class InventoryStat(models.Model):
    """Inventory_stat models"""
    inv_station_no = models.CharField(max_length=8)
    station_description = models.CharField(max_length=20)
    is_delete = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.station_description

class CostCenter(models.Model):
    """Cost_center models"""
    cost_center_name = models.CharField(max_length=40)
    inv_station_no = models.ForeignKey(InventoryStat, related_name="i_ccFK")
    functional_group = models.CharField(max_length=40)
    is_delete = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.cost_center_name


class Employee(models.Model):
    """Employee models"""
    dce = models.CharField(max_length=8, primary_key=True)
    name = models.CharField(max_length=40)
    cost_center_no = models.ForeignKey(CostCenter, related_name="cc_eFK")
    charging_cc_no = models.CharField(max_length=20)
    position = models.CharField(max_length=20)
    history = HistoricalRecords()
    is_delete = models.BooleanField(default=False)
    user_id = models.ForeignKey(User, default=1)
    """user = User.objects.create_user(username='guest',
                                 email='', id=1,
                                 password='guest')"""
    user_id = models.ForeignKey(User, default=1)

    def __str__(self):
        return self.name


class Customer(models.Model):
    """Customer models"""
    dce = models.ForeignKey(Employee, related_name="d_cFK")
    credit_limit = models.FloatField()
    debit_amount = models.FloatField()
    credit_amount = models.FloatField()
    balance_amount = models.FloatField()
    history = HistoricalRecords()

    def __str__(self):
        return self.dce


class Product(models.Model):
    """Product models"""
    nsn = models.CharField(max_length=15)
    slc_number = models.CharField(max_length=15)
    generic_name = models.CharField(max_length=40)
    item_name = models.CharField(max_length=40)
    brand = models.CharField(max_length=40)
    part_number = models.CharField(max_length=8)
    manufacture_date = models.DateField()
    expiry_date = models.DateField(null=True, blank=True)
    unit_cost = models.FloatField()
    quantity = models.PositiveIntegerField(default=1)
    classification = models.CharField(max_length=30)
    stock = models.CharField(max_length=10)
    block = models.CharField(max_length=10)
    unit_measure = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    purchased_from = models.ForeignKey(Supplier, related_name="s_pFK")
    average_amount = models.FloatField(default=0)
    balance_limit = models.FloatField()
    serial_number = models.CharField(max_length=25, null=True, blank=True)
    model = models.CharField(max_length=25)
    amount = models.FloatField()
    description = models.CharField(max_length=40)
    remarks = models.CharField(max_length=40, null=True, blank=True)
    history = HistoricalRecords()
    inv_station_no = models.ForeignKey(InventoryStat, related_name="inv_iFK")
    balance = models.PositiveIntegerField(default=0, null=True, blank=True)
    is_irr = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name + " , " + self.description


class IRRHeader(models.Model):
    """IRR_header models"""
    inv_station_no = models.ForeignKey(InventoryStat, related_name="is_iFK")
    reference = models.CharField(max_length=20)
    invoice_number = models.CharField(max_length=20)
    po_number = models.CharField(max_length=20)
    pr_number = models.CharField(max_length=20)
    dr_number = models.CharField(max_length=20)
    dce_custodian = models.ForeignKey(Employee, related_name='dce1')
    dce_user = models.ForeignKey(Employee, related_name='dce2')
    dce_approved = models.ForeignKey(Employee, related_name='dce3')
    proc_date = models.DateField(null=True, blank=True)
    approved_date = models.DateField(null=True, blank=True)
    type_n = models.CharField(max_length=20)
    date_dlvrd = models.DateField()
    supplier = models.ForeignKey(Supplier, related_name="s_iFK")
    history = HistoricalRecords()

    def __str__(self):
        return str(self.id)

    class Meta:
        unique_together = (("po_number", "pr_number", "supplier"),)


class IRR(models.Model):
    """IRR models"""
    product = JSONField()
    irr_headkey = models.ForeignKey(IRRHeader, related_name="ih_iFK")
    irr_no = models.CharField(max_length=10, primary_key=True)
    cost_center_no = models.ForeignKey(CostCenter, related_name="ccn_iFK")
    date_recv = models.DateField()
    wo_no = models.CharField(max_length=10)
    wrs_number = models.CharField(max_length=8)
    remarks = models.CharField(max_length=40, null=True, blank=True)
    is_par = models.BooleanField(default=False)
    is_miv = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.irr_no)



class MIV(models.Model):
    """MIV models"""
    miv_no = models.CharField(max_length=10, primary_key=True)
    irr_no = models.ForeignKey(IRR, related_name="i_mFK")
    date_issued = models.DateField()
    doc_date = models.DateField()
    remarks = models.CharField(max_length=40, null=True, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.irr_no)


class PAR(models.Model):
    """PAR models"""
    product = JSONField()
    dce = models.ForeignKey(Employee, related_name="d_pFK")
    par_date = models.DateField()
    par_no = models.CharField(max_length=10, primary_key=True)
    amt_cost = models.FloatField()
    remarks = models.CharField(max_length=40, null=True, blank=True)
    approved_by = models.ForeignKey(Employee, related_name='dce_FK2')
    issued_by = models.ForeignKey(Employee, related_name='dce_FK3')
    inv_stat_no = models.ForeignKey(InventoryStat, related_name="is_pFK")
    date_acquired = models.DateField()
    wo_number = models.PositiveIntegerField(default=0)
    is_garv = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return self.par_no

class GARV(models.Model):
    """GARV models"""
    product_to_GARV = JSONField()
    dce = models.ForeignKey(Employee, related_name="d_gFK")
    garv_date = models.DateField()
    garv_no = models.CharField(max_length=10, primary_key=True)
    cc_number = models.CharField(max_length=8)
    wo_number = models.PositiveIntegerField()
    inspected_by = models.ForeignKey(Employee, related_name='dce_FK4')
    date_inspected = models.DateField(null=True, blank=True)
    confirmed_by = models.ForeignKey(Employee, related_name='dce_FK5')
    date_confirmed = models.DateField(null=True, blank=True)
    noted_by = models.ForeignKey(Employee, related_name='dce_FK6')
    is_approved = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.garv_no)

class WRSPending(models.Model):
    """WRSPending models"""
    product = JSONField()
    inv_station_no = models.ForeignKey(InventoryStat, related_name="inv_wFK")
    cost_center_no = models.ForeignKey(CostCenter, related_name="cc_wFK")
    wrs_number = models.CharField(max_length=8)

    def __str__(self):
        return str(self.inv_station_no)

class Unit_Measure(models.Model):
    """unit measure"""
    unit_measure = models.CharField(max_length = 30)

    def __str__(self):
        return str(self.unit_measure)

WOS/WISH/templates/WISH/cost_center_form.html
<!--style="font-family: 'Cinzel', serif;"-->
{% extends 'WISH/index.html' %}
{% block content %}
{% load bootstrap %}

<style type="text/css">
        .form-group{
          width:300px;
        }
      </style>
    <div class="page-header">
        	<!--<img src=""></img>-->
       	<h2 align="center">Cost Center Record</h2>
	</div>
  {%if msg%}
  <div class="alert alert-success" style="width:400px">
      {{ msg }}
  </div>
  {% endif %}

    <form method="POST" class="product-form">{% csrf_token %}

  <table width="50%" align="center" >

     {% for field in form %}
      {{field | bootstrap}}&nbsp;&nbsp;&nbsp;
     {%endfor%}


  </table>
     <div align="center"><button type="submit" class="save btn btn-default">Save</button></div>
    </form>
{% endblock %}

WOS/WISH/templates/WISH/costcenter_detail.html
{% extends 'WISH/index.html' %}
{% load staticfiles %}
 {% block content %}
<html>
    <head>
        <title>Cost Center details</title>
        <style type="text/css" >
        	th, td {
        		padding: 5px
        	}
        </style>
    </head>
<br><br>
    <body>
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/details.css' %}">
      <div class="container">
              <div class="row text-center">
                  <div class="col-md-12" style="margin-top: 20px;">
                      <div class="pricing-table">
                          <div class="panel panel-primary" style="border: none;">
                              <div class="controle-header panel-heading panel-heading-landing">
                                  <h1 class="panel-title panel-title-landing">
                                    Cost Center
                                  </h1>
                              </div>
                              <div class="controle-panel-heading panel-heading panel-heading-landing-box">
                                  Details
                              </div>
                              <div class="panel-body panel-body-landing">
                                  <table class="table" style="text-align: center">
                                      <tr>
                                          <td width="50%">Cost Center Name :</td>
                                          <td>{{cc.cost_center_name}}</td>
                                      </tr>
                                      <tr>
                                          <td width="50px">Functional Group : </td>
                                          <td>{{cc.functional_group}}</td>
                                      </tr>

                                  </table>
                              </div>
                              {% if request.user.is_superuser %}
                              <div class="panel-footer panel-footer-landing">
                                  <a href="{% url 'costcen_entry' pk=cc.pk %}" class="btn btn-price btn-info btn-lg">Edit</a>
                                  <a href="{% url 'costcen_del' pk=cc.pk %}" class="btn btn-price btn-info btn-lg">Delete</a>

                              </div>
                              {% endif %}
                          </div>
                      </div>
                  </div>
              </div>
          </div>
    </body>

</html>

{% endblock %}

WOS/WISH/templates/WISH/inv_stat_form.html
<!--style="font-family: 'Cinzel', serif;"-->
{% extends 'WISH/index.html' %}
{% block content %}
{% load bootstrap %}

<style type="text/css">
        .form-group{
          width:300px;
        }
      </style>
    <div class="page-header">
        	<!--<img src=""></img>-->
       	<h2 align="center">Inventory Station Record</h2>
	</div>
  {%if msg%}
  <div class="alert alert-success" style="width:400px">
      {{ msg }}
  </div>
  {% endif %}

    <form method="POST" class="product-form">{% csrf_token %}

  <table width="50%" align="center" >

     {% for field in form %}
      {{field | bootstrap}}&nbsp;&nbsp;&nbsp;
     {%endfor%}


  </table>
     <div align="center"><button type="submit" class="save btn btn-default">Save</button></div>
    </form>
{% endblock %}

WOS/WISH/templates/WISH/irr_reports.html
{% extends 'WISH/index.html' %}

{% block content %}
<div class="container" style="width:60%;">

<ul class="nav nav-tabs" role="tablist">
      <li class="active">
          <a id='irrb' href="{% url 'irr_reports' %}">
              IRR Reports
          </a>
      </li>
      <li>
          <a id='mivb' href="{% url 'miv_reports' %}" >
              MIV Reports
          </a>
      </li>
       <li>
          <a id='wrsb' href="{% url 'wrs_reports' %}">
              WRS Reports
          </a>
      </li>
      <li>
          <a id='parb' href="{% url 'par_reports' %}">
              PAR Reports
          </a>
      </li>
      <li>
          <a id='garvb' href="{% url 'garv_reports' %}">
              GARV Reports
          </a>
      </li>
    </ul>
<div id="irr">
  <br>
  <div class="col-md-2" align='left'>
    <form action="" method="get">
      <div class="input-group">
        <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
          <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
      </div>
    </form>

  </div>
{% if irr_list|length == 0 and error %}


    <div class="alert alert-warning" style="width:400px">
      {{error}}
    </div>


{% elif irr_list|length == 0 %}
    <br>
    <br>
      <div class="alert alert-warning" style="width:400px">
        No IRR Record(s) found for this month.
      </div>
{% else %}

<div class="col-md-8">
       <table class="table table-list-search">
         {%if msg%}
           <div class="alert alert-success" style="width:400px">
             {{ msg }}
           </div>
         {% endif %}
    <thead>
     	<th><center>IRR NO.</center></th>
       <th><center>COST CENTER NAME</center></th>
       <th><center>DATE RECEIVED</center></th>
       <th><center>WORK ORDER NO.</center></th>

    </thead>

       <tbody id="myTable">


     	  {% for irr in irr_list %}
      	 <tr>
           <td>
              <a href="{% url 'irr_form' pk=irr.pk %}">
              <center>{{ irr.pk }}</center>
              </a>
            </td>
           <td>
              <center>{{irr.cost_center_no}}</center>
           </td>
           <td>
              <center>{{irr.date_recv}}</center>
           </td>
           <td>
              <center>{{irr.wo_no}}</center>
           </td>
      	 </tr>
      {% endfor %}
      </tbody>
  </table>
  {% endif %}
  </div>
  </div>

<script type="text/javascript">
  $(document).ready(function() {
    var activeSystemClass = $('.list-group-item.active');

    //something is entered in search form
    $('#system-search').keyup( function() {
       var that = this;
        // affect all table rows on in systems table
       var tableBody = $('.table-list-search tbody');
        var tableRowsClass = $('.table-list-search tbody tr');
        $('.search-sf').remove();
        tableRowsClass.each( function(i, val) {
        
            //Lower text for case insensitive
            var rowText = $(val).text().toLowerCase();
            var inputText = $(that).val().toLowerCase();
            if(inputText != '')
            {
                $('.search-query-sf').remove();
                tableBody.prepend('<tr class="search-query-sf"><td colspan="6"><strong>Searching for: "'
                    + $(that).val()
                    + '"</strong></td></tr>');
            }
            else
            {
                $('.search-query-sf').remove();
            }

            if( rowText.indexOf( inputText ) == -1 )
            {
                //hide rows
                tableRowsClass.eq(i).hide();
                
            }
            else
            {
                $('.search-sf').remove();
                tableRowsClass.eq(i).show();
            }
        });
        //all tr elements are hidden
        if(tableRowsClass.children(':visible').length == 0)
        {
            tableBody.append('<tr class="search-sf"><td class="text-muted" colspan="6">This entry is not found in this monthly list.' + 
              '<br>Just hit the Enter button to search further.</td></tr>');
        }
    });
});
  </script>

{% endblock %}

WOS/WISH/templates/WISH/miv_entry_f.html
{% extends 'WISH/index.html' %}

{% block content %}

{% if irr_list|length == 0 %}

  <div class="alert alert-warning" style="width:400px">
    No IRR Record(s) to be made with MIV Record.
  </div>
  <div align="center"><a href= "{% url 'index' %}"><i class="glyphicon glyphicon-share-alt"></i> Exit </a></div>

{% else %}
  <!-- Start of header -->
  <div class="page-header">
    <h2 align="center">Select IRR Record to be created with MIV Report</h2>
  </div>
  <!-- End of header -->

  <!-- Start of search input form-->
  {% if irr_list|length <= 20 %}
    <div class="col-md-2" style="margin-left: 160px"></div>
  {% else %}
    <div class="col-md-2" style="padding-right: 0px; margin-left: 300px; padding-left: 0px;">
    <form action="#" method="get">
      <div class="input-group">
        <!-- USE TWITTER TYPEAHEAD JSON WITH API TO SEARCH -->
        <input class="form-control" id="system-search" name="q" placeholder="Search for" required>
      </div>
    </form>
  </div>
  {% endif %}
  <!-- End of search input form -->
  
  <div class="col-md-5" style="padding-left: 10px;">
      <!-- Start of table -->
      <table class="table table-list-search" width="50px" style="text-align:center">    
          <thead>
           	<th>IRR No.</th>
             <th>Cost Center Name</th>
             <th>Date Received</th>
             <th>Work Order No.</th>
          </thead>
          {% for irr in irr_list %}
          	<tr>
              <td>
                <a href="{% url 'new_miv_s' pk=irr.pk %}">
                  {{ irr.irr_no}}
                </a>
              </td>
            </td>
            <td>
              {{irr.cost_center_no}}
            </td>
            <td>
              {{irr.date_recv}}
            </td>
            <td>
              {{irr.wo_no}}
            </td>
          	</tr>
          {% endfor %}
      </table>
      <!-- End of table -->
  </div>
  {% endif %}
{% endblock %}
<!-- Start of script for automatic search -->
<script type="text/javascript">
  $(document).ready(function() {
    var activeSystemClass = $('.list-group-item.active');

    //something is entered in search form
    $('#system-search').keyup( function() {
       var that = this;
        // affect all table rows on in systems table
        var tableBody = $('.table-list-search tbody');
        var tableRowsClass = $('.table-list-search tbody tr');
        $('.search-sf').remove();
        tableRowsClass.each( function(i, val) {
        
            //Lower text for case insensitive
            var rowText = $(val).text().toLowerCase();
            var inputText = $(that).val().toLowerCase();
            if(inputText != '')
            {
                $('.search-query-sf').remove();
                tableBody.prepend('<tr class="search-query-sf"><td colspan="6"><strong>Searching for: "'
                    + $(that).val()
                    + '"</strong></td></tr>');
            }
            else
            {
                $('.search-query-sf').remove();
            }

            if( rowText.indexOf( inputText ) == -1 )
            {
                //hide rows
                tableRowsClass.eq(i).hide();
                
            }
            else
            {
                $('.search-sf').remove();
                tableRowsClass.eq(i).show();
            }
        });
        //all tr elements are hidden
        if(tableRowsClass.children(':visible').length == 0)
        {
            tableBody.append('<tr class="search-sf"><td class="text-muted" colspan="6">No entries found.</td></tr>');
        }
    }); 
  });
</script>
<!-- End of script for automatic search -->